[package]
name = "dkim-verifier-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
trust-dns-resolver = "0.19"

[[bin]]
name = "email-dkim-verifier-contract"
path = "src/main.rs"
