[package]
name = "email-dkim-verifier-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "5.17.2" }
borsh = "1.5"
sha2 = "0.10"
base64 = "0.13"
rsa = "0.3.0"

[features]
unit-testing = ["near-sdk/unit-testing"]
